### ISSUE TITLE
Incorrect lemonade.apply signature in documentation vs code!

### ISSUE THREAD

**Issue by FrontEndNeo** [lemonadejs/lemonadejs#10]
Could you please correct the documentation or the code

In the website documentation
lemonade.apply(self, DOMElement)

![image](https://user-images.githubusercontent.com/62092276/158423285-9dd03cad-8d93-4588-9de2-bf393125c275.png)

In the library code
L.apply(DOMElement, self)

![image](https://user-images.githubusercontent.com/62092276/158423580-2a190afa-132b-4c82-b034-d56dd0cc0c38.png)

Thanks ☺

**Comment by sucom** [comment]
Hi @hodeware, which one is correct? the site documentation or the code? I don't see any changes in the site documentation or in the code v.2.4.2!!! but you have closed the issue!

**Comment by hodeware** [comment]
apply(DOM, self); documention has been updated.

**Comment by FrontEndNeo** [comment]
Hi @hodeware, I don't see the changes in the website. Please visit https://lemonadejs.net/v2/docs/quick-reference and scroll to Methods section and this is what I see 

![image](https://user-images.githubusercontent.com/62092276/158738567-fe974be2-072f-42e3-a8b6-ff993ec098b5.png)
