### ISSUE TITLE
contact not reachable

### ISSUE THREAD

**Issue by FrontEndNeo** [lemonadejs/lemonadejs#11]
The contact details on package.json is not reachable!

I would like to share few things with the dev / documentation team. Unable to reach 

![image](https://user-images.githubusercontent.com/62092276/158426051-05d37f86-127b-4415-9bc5-c28aa281a679.png)

![image](https://user-images.githubusercontent.com/62092276/158426107-54eafb3b-659d-442f-a9ca-d15d60694c7f.png)

from the site
![image](https://user-images.githubusercontent.com/62092276/158426276-d2571b09-71c8-4d86-9837-5f9e3be8e36f.png)

but no response!

**Comment by hodeware** [comment]
Please use: contact@jspreadsheet.com for now. We will make sure the email is working soon.
