### ISSUE TITLE
bind & loop problem

### ISSUE THREAD

**Issue by celeg** [lemonadejs/lemonadejs#22]
I try to use `@bind` & `@loop`. i share the code https://codesandbox.io/s/quirky-lake-l7ed9w?file=/src/App.js
```
let self = {
   ...
    a: "Alberto",
    b: {
      name: "John",
      age: 26,
      email: "john@doe.com"
    },
    c: [
      {
        name: "Albert",
        age: 38,
        email: "alberto@email.com"
      }
    ],
    d: [
      {
        name: "Albert",
        age: 38,
        email: "alberto@email.com"
      },
      {
        name: "Alberto",
        age: 26,
        email: "albert@email.com"
      },
      {
        name: "Sylvain",
        age: 57,
        email: "sylvain@email.com"
      }
    ]
  };
```

if i use @bind  for `self.a` or `self.d` this work , but not just simple object as `self.b` . I try different test with `self.c` but same problem.
For @loop, see the code, if i use two time , the first loop appears in second loop.
![Capture](https://user-images.githubusercontent.com/2057327/159945097-4633efc4-da49-41c6-a2aa-f2fdabdc86fb.JPG)

**Comment by hodeware** [comment]
You can only use the first level properties from the self.

self.b.name <= this is wrong. you need to use only properties directly in the self.

**Comment by celeg** [comment]
See the loop here : https://codesandbox.io/s/loop-error-7kq48j
What is the wrong code ?

**Comment by hodeware** [comment]
Use different loops. Using the loop, each element of the array gets a DOM element assigned. A DOM Element cannot be in two different locations at the same time. So, you cannot use the same property in two loops.
