### ISSUE TITLE
<select> @bind @loop

### ISSUE THREAD

**Issue by celeg** [lemonadejs/lemonadejs#24]
How work bind and loop into select (and get value of option selected) and we have access to increment number of loop ? 

i try this https://codesandbox.io/s/lemonadejs-select-loop-hux4o9?file=/index.html

**Comment by hodeware** [comment]
You can do something like that:

```
  let template = `<>
    <select @bind='self.value' @loop='self.options'>
      <option value='{{self.id}}'>{{self.name}}</option>
    </select>    
    <br />
    <small>{{self.value}}</small>
  </>`;
```

To get the incremental number of loop, you can use indexOf(self).

**Comment by celeg** [comment]
i have change the code in the previews link, Okay, but can you show me for the indexOf, how to implement this in the template ?
