### ISSUE TITLE
Refresh data on newly added element in the dom after calling "apply"

### ISSUE THREAD

**Issue by soinalastudio** [lemonadejs/lemonadejs#27]
Hello,
How to "refresh" data on a newly appended element (added dynamically) in the dom please after calling "apply"? 

Thank you so much,

**Comment by hodeware** [comment]
There is three ways:

1) You keep access to the self you have applied. The refresh method will be created automatically.

self.refresh('property-that-is-array-and-you-want-to-refresh');

2) Second option is recover the instance of the self from the DOM Element

yourRootDOM.lemon.self.refresh('property-that-is-array-and-you-want-to-refresh');

3) Use SUGAR to keep access to your self. Them use dispatch to refresh.
