### ISSUE TITLE
Question: Is there expanded notations for @ref, @bind, @loop and @ready

### ISSUE THREAD

**Issue by Mashiane** [lemonadejs/lemonadejs#28]
Hi there

Is there an expanded notation for these shortcuts?

@ref, @bind, @loop and @ready?

For example, in vuejs one can use v-bind or v-on as the @ sign is recognized as a shortcut. Do you have an alternative also that one can use e.g @bind can also be written as ljs-bind as an example?

Thanks, lovely work.

**Comment by hodeware** [comment]
Make sense, we will add that soon.

**Comment by hodeware** [comment]
That has been included.
