### ISSUE TITLE
Failed to refresh in nested UI object

### ISSUE THREAD

**Issue by samsam88swd** [lemonadejs/lemonadejs#29]
Hi,

I found that refresh in first level json object is possible (see "Del page" link), but unable to refresh second level json object (see "Add field" link), is there any wrong thing I did? Many thanks.

<html>
<script src="https://lemonadejs.net/v2/lemonade.js"></script>

<div id='root'></div>
<script>
const Component = function() {
    var self = {};
 
    self.addPage = function() {
        self.data.push({ title: self.text });
        self.refresh('data');
        self.text = '';
		console.log(JSON.stringify(self.data));
    }

    self.data = {
   "name":"Item 1",
   "number":1,
   "pages":[
      {
         "id":"8ca78c36-8373-4f23-94ba-111",
         "fields":[
            
         ]
      },
      {
         "id":"8ca78c36-8373-4f23-94ba-222",
         "fields":[
            {
               "fieldid":"66ef0525-16f1-48e7-8ad1-29c8c6c62c72"
            }
         ]
      },
      {
         "id":"8ca78c36-8373-4f23-94ba-333",
         "fields":[
            {
               "fieldid":"91b0dbf1-df29-4a9e-b22d-9a392f91a32c"
            }
         ]
      }
   ]
};

    self.addpage = function() {
		
        self.data.pages.push({ id: "newId"});
        self.refresh('data');
        self.text = '';
    }
 

     self.addfield = function(s) {
		for (var i=0; i<self.data.pages.length; i++)
		{
			if (self.data.pages[i].id == s.id)
			{
				self.data.pages[i].fields.push({ id: "newId"});
				break;
			}
		}
		self.refresh('data');
    }

    self.delpage = function(s) {
        self.data.pages.splice(self.data.pages.indexOf(s), 1);
        self.refresh('data');
		console.log(JSON.stringify(self.data));
    }
 
    var template = `<>
            <ul @loop="self.data.pages">
                <li>
                    <i>{{self.id}}</i>
					<span onclick="self.parent.delpage(self)" style="cursor: pointer;">(Del page)</span>
					<span onclick="self.parent.addfield(self)" style="cursor: pointer;">(Add field)</span>
						<ul @loop="self.fields">
							<li>
			                    <i>{{self.fieldid}}</i>
								q
							</li>
						</ul>
				</li>
            </ul>
            <input type="text" @bind="self.text" />
            <input type="button" value="Add Page" onclick="self.addpage()" />
            <input type="button" value="Debug" onclick="self.debug()" />
        </>`;
 
    return lemonade.element(template, self);
}
lemonade.render(Component, document.getElementById('root'));
</script>
</html>

**Comment by hodeware** [comment]
That is a known limitation. @loop should be used in first level object properties.
