### ISSUE TITLE
Cannot use the import statement for loading LemonadeJS

### ISSUE THREAD

**Issue by lucianoiam** [lemonadejs/lemonadejs#32]
`import './lemonade.js'` results in cryptic errors which vary across browsers. For example on Safari:

`lemonade.js:18 Uncaught TypeError: Cannot set properties of undefined (setting 'lemonade')`

I worked around this by creating a small loader module but I think it would be nice to be able to just write `import './lemonade.js'`

lemonade-loader.js
```JS

await loadScript('lemonade.js');

async function loadScript(src) {
    return new Promise((resolve, reject) => {
        const el = document.createElement('script');
        el.src = src;
        el.onerror = reject;
        el.onload = _ => resolve(el);
        document.head.appendChild(el);
    });
}

```

app.js
```JS
import './lemonade-loader.js';

```

**Comment by hodeware** [comment]
Can you send real world example on where you would like to use import?

**Comment by lucianoiam** [comment]
The project I'm working on is still private on GitHub but follows the following structure seen [here](https://github.com/lucianoiam/consul/blob/master/src/ui/index.html)

The index document imports the main "app" as a module, and then all assets and scripts are loaded during runtime delegating the responsibility to the app. Shorter, no more than a single <script> in index.html. This can be still achieved by the workaround described above, but I wonder what are the reasons that prevent this scheme from working with LemonadeJS.

Maybe it helps mentioning I am not using any intermediate tools like webpack, transpilers, etc. I work on an embedded-like environment (audio plugins) with as few layers as possible, no dependencies and hand-written JavaScript. In that sense I picked LemonadeJS because it provides reactive views without all the unnecessary bloat in this setup.

**Comment by lucianoiam** [comment]
React cannot be imported as a module on a browser yet. [This project](https://github.com/lukejacksonn/es-react) has 200+ stars and addresses the same issue but for React, guess there are more use cases.

**Comment by hodeware** [comment]
Thanks, I will definetely take a look...

**Comment by hodeware** [comment]
We have released the new LemonadeJS v3. Now, you can load that as a module as follow.
https://lemonadejs.net/v3/docs/module

In regards to Webcomponents, you can inject LemonadeJS and create a reactive webcomponent.
https://lemonadejs.net/v3/docs/web-components
