### ISSUE TITLE
Initial state for function vs class based components

### ISSUE THREAD

**Issue by lucianoiam** [lemonadejs/lemonadejs#34]
Likely not an issue but my incomplete understanding. By the way is there a better place for asking questions?

I am trying to implement custom (LemonadeJS) components as ES6 classes, and realized attributes are not being read from the tag. Take this example from a parent component markup:

`<Hello title="The very best of 2022" />`

This renders fine (copied from one of the library examples):

```JavaScript
function Hello() {
    // Get the attributes from the tag
    let self = this;
 
    // Title and year are declared in the parent template
    let template = `<h1>{{self.title}} {{self.year}}</h1>`;
 
    return lemonade.element(template, self);
}
```

This does not (self.title renders empty):

```JavaScript
class Hello extends lemonade.component {

    render() {
        return lemonade.element(`<h1>{{self.title}} {{self.year}}</h1>`, this);
    }

}
```

Except from the initial value the parent tries to set, everything seems to work fine with the class-based Hello component.

**Comment by hodeware** [comment]
In the classes render does not return lemonade.element, only the template as the example below:

```
<html>
<script src="https://lemonadejs.net/v2/lemonade.js"></script>
<div id='root'></div>
<script>
class Counter extends lemonade.component {
    constructor() {
        super();
        this.count = 1;
    }
 
    counter() {
        this.count++;
    }
 
    render() {
        return `
            <>
            <div>Counter: {{self.count}}</div><br>
            <input type='button' onclick="self.counter()" value='Go' />
            <input type='button' onclick="self.count = 0" value='Reset' />
            </>
        `;
    }
}
lemonade.render(Counter, document.getElementById('root'));
</script>
</html>
```

**Comment by hodeware** [comment]
I am creating an example for you....

**Comment by lucianoiam** [comment]
It still does not work

```
<html>
<script src="https://lemonadejs.net/v2/lemonade.js"></script>
<div id='root'></div>
<script>

function FunctionComponent() {
    let self = this;
    let template = `<h1>{{self.title}}</h1>`;
 
    return lemonade.element(template, self);
}

class ClassComponent extends lemonade.component {

    render() {
        return `<h1>{{self.title}}</h1>`;
    }

}

function MainView() {
    let template = `<>
        <FunctionComponent title="Test message for function" />
        <ClassComponent title="Test message for class" />
    </>`;
 
    return lemonade.element(template, self, { FunctionComponent, ClassComponent });
}

lemonade.render(MainView, document.getElementById('root'));
</script>
</html>
```

IMHO it is better to create examples in the documentation rather than just for me

**Comment by hodeware** [comment]
Yes, there a few examples worth uploading to the documentation. A new section for webcomponents will be added...

**Comment by hodeware** [comment]
In the current version, the self for classes goes in the constructor where you need to do the merge. I noticed that @ref is not working correctly so you need to create the reference in the parent manually.

We are currently working on LemonadeJS v3, which this issue will be addressed.

```
    class Hello extends lemonade.component {
        constructor(self) {
            super(self);
            // Initial self
            Object.assign(this, self);
            // Keep the reference of this instance in the parent
            o.parent.hello = this;
        }

        render() {
            return `<h1>{{self.title}}</h1>`;
        }
    }

    function Test() {
        // Get the attributes from the tag
        let self = this;

        // Title and year are declared in the parent template
        let template = `<div>
            <Hello title="The very best of 2022" />
          <input type="button" onclick="self.hello.title = 'new title'" value="Change title"/>
          </div>`;

        return lemonade.element(template, self, { Hello });
    }

    lemonade.render(Test, document.getElementById('root'));
```

**Comment by lucianoiam** [comment]
It is now unclear the scenario described in this issue report is a bug or a feature.

The snippet throws an error: ReferenceError: Can't find variable: o

<img width="803" alt="Screenshot 2022-12-27 at 14 21 03" src="https://user-images.githubusercontent.com/930494/209673012-8ca0d61b-f720-475b-bcd7-4125e6806e39.png">

**Comment by hodeware** [comment]
Sorry, my bad... change o.parent.hello to self.parent.hello = this

**Comment by lucianoiam** [comment]
Cool, `Object.assign()` does the trick. The final version of a custom_HTML5_Web_Component to LemonadeJS_component wrapper using a ES6 class so far looks like this:

```JS

export class KnobComponent extends lemonade.component {

    constructor(self) {
        super(self);

        // This will read values set by attributes
        // for example: <KnobComponent min="1" max="100" value="1" />
        Object.assign(this, self);

        // Defaults
        this.min = this.min || 0;
        this.max = this.max || 1;
        this.value = this.value || 0.5;
    }

    render() {
        return `<g-knob
                    min="{{self.min}}"
                    max="{{self.max}}"
                    @bind="self.value">
                </g-knob>`;
    }

}

```

**Comment by lucianoiam** [comment]
More testing... initial state is now correctly set, but the component is not reactive.  Just noticed this was sneaked into the example snippet, kinda defeats the purpose of the library...

>           <input type="button" onclick="self.hello.title = 'new title'" value="Change title"/>

The only complete solution is to forget ES6 classes and use functions which is totally fine but undocumented:

```JS
export function KnobComponent() {
    let self = this;

    const template = `<g-knob
                        min="{{self.min}}"
                        max="{{self.max}}"
                        @bind="self.value">
                      </g-knob>`;

    return lemonade.element(template, self);

}
```

**Comment by hodeware** [comment]
I am not sure why is not working for you, but take a look here. It is reacting to the button...
https://jsfiddle.net/nf6a5o8u/5/

**Comment by lucianoiam** [comment]
This example focus on the discrepancies between function and class. It correctly sets the initial value (100) for both, because the class version contains the `Object.assign()` hack. But then only the function component gets updated in response to the timer... do you think there is something wrong in this code?

```
<html>
<script src="https://lemonadejs.net/v2/lemonade.js"></script>
<div id='root'></div>
<script>

function FunctionComponent() {
    let self = this;
    let template = `<h1>{{self.value}}</h1>`;
 
    return lemonade.element(template, self);
}

class ClassComponent extends lemonade.component {

    constructor(self) {
        super(self);
        Object.assign(this, self);
    }

    render() {
        return `<h1>{{self.value}}</h1>`;
    }

}

function MainView() {
    let self = this;

    self.value = 100;

    setInterval(() => {
        self.value++;
    }, 1000);

    let template = `<>
        <FunctionComponent value="{{self.value}}" />
        <ClassComponent value="{{self.value}}" />
    </>`;
 
    return lemonade.element(template, self, { FunctionComponent, ClassComponent });
}

lemonade.render(MainView, document.getElementById('root'));
</script>
</html>
```

**Comment by hodeware** [comment]
Thanks, I will check that and come back to you

**Comment by hodeware** [comment]
Yes, that was a problem which has been fixed. Thanks for the example.
https://jsfiddle.net/nf6a5o8u/12/

**Comment by hodeware** [comment]
You don't need to use Object.assign anymore...

**Comment by hodeware** [comment]
But, @ref still a problem which only be fixed on version 3.

**Comment by lucianoiam** [comment]
I confirm everything now works as expected, thanks.

**Comment by lucianoiam** [comment]
By the way, is it possible to set a default state within the class implementation while retaining the ability of reading the initial state from attributes? or both things are mutually exclusive?

**Comment by hodeware** [comment]
Yes, you can overwrite the value from the initial value defined in the tag.

**Comment by lucianoiam** [comment]
This construct seems to work for every case, if there is a simpler/better way let me know.

```
    constructor(self) {
        super(self);

        this.min = self.min || 0;
        this.max = self.max || 1;
        this.value = self.value || 0.5;
    }
```

**Comment by hodeware** [comment]
That's correct.
