### ISSUE TITLE
Improving the syntax (inspiring from reactjs)

### ISSUE THREAD

**Issue by Kivylius** [lemonadejs/lemonadejs#35]
This is more a question/sujestion from the react side of devs to make the switch easier. Could we have something like this:

```jsx

class HelloElement extends CustomLemonadeHTML {
    static title = "";
    constructor() {
        super("hello-element");
    }
 
    render() {
        return (
             <>
                 <h1>title: {this.title}</h1>
                 <input type="button" value="setTitle" onclick={() => this.title = "test"} />
             </>
        );
    }
}
```

This obviously psudo code, but its clean syntax that would work well for react devs, like myself, to switch from react -> web components.

**Comment by hodeware** [comment]
Thanks for the suggestion. The idea for LemonadeJS to avoid jsx to avoid compilation. In regards to the double marks {{ }}, is avoid conflicts with the the text and last {this} can cause a lot of confusion, example:

<div onclick="self.click(this)"></div>
<div onclick="this.click()"></div>

The first one, sends {this} which this is the HTML element <div>, and that is closer to what expect from Vanilla JS.

With LemonadeJS you can do things like this
<div style="display: {{self.visibility?'block':'none'"}}>test</div>

That will be reactive, if you change self visibility that will not render everything again, but only update the style attribute.
