### ISSUE TITLE
Bug - Components doesn't show on the site

### ISSUE THREAD

**Issue by GridexX** [lemonadejs/lemonadejs#5]
## Context
On the website, there are some examples of use.
It contains code preview and the result to the right.

**When getting on the site, results are not working.**

Here are some screenshots : 
**-> Counter aren't show as they should**

![image](https://user-images.githubusercontent.com/50552672/157000689-d506eb65-cd43-4e84-830d-1bbb7da9436c.png)

![image](https://user-images.githubusercontent.com/50552672/157000739-ce8e950f-e0f6-4e3f-ae61-a28a1338e2c2.png)

## Architecture

Operating System : Kubuntu 20.04 KDE Plasma 5.18.8
Browser :
- Firefox 97.0.2
- Extensions : Ghostery, uBlock Origin 1.41.8, https://Everywhere Version: 2021.7.13,

**Comment by hodeware** [comment]
That has been fixed.
