### ISSUE TITLE
Website Code block background is too dark and code is not readable

### ISSUE THREAD

**Issue by FrontEndNeo** [lemonadejs/lemonadejs#7]
The code blocks not visible properly in the website! [LemonadeJs Website](https://lemonadejs.net/v2/)

Please see the screenshot below

![image](https://user-images.githubusercontent.com/62092276/158191064-96b50438-3963-46bc-a20d-6fe8eaf39f79.png)

Fix: code.css -> .prettyprint { background: #ddd} will fix this issue

Please see the screenshot below after fixing the css

![image](https://user-images.githubusercontent.com/62092276/158191962-819c774f-9a84-44a2-b5f2-909a7ac8a6af.png)

Thanks ☺

**Comment by hodeware** [comment]
I believe that should be a temporary connection problem. That happens when a CSS is not completed loaded. Hopefully that is better today.

**Comment by FrontEndNeo** [comment]
Hi, It is not network connection problem. The theme [css file](https://lemonadejs.net/templates/default/css/code.css) is loaded correctly. 

https://lemonadejs.net/templates/default/css/code.css

```
/*! Color themes for Google Code Prettify | MIT License | github.com/jmblog/color-themes-for-google-code-prettify */
.prettyprint {
    box-sizing: border-box;
    background: #1d1f21;
    font-family: Menlo,Bitstream Vera Sans Mono,DejaVu Sans Mono,Monaco,Consolas,monospace;
    border: 0!important;
    padding: 20px !important;
    border-radius: 6px;
}
```
The background color #1d1f21 is too dark and makes the code block unreadable. Please change to #ddd, so the code block will be readable.

If you still believe it's a network issue at my end, could you please share the screenshot of the site home page with the code block from your browser, So, I could check at my end.

Note, I tested the site on Windows and Mac, Edge,Chrome,Firefox and Safari.

Thanks.

**Comment by FrontEndNeo** [comment]
How to fix this issue?

![image](https://user-images.githubusercontent.com/62092276/158302220-b8831388-34b8-4966-a0e8-3383e08a5f2f.png)

**Comment by FrontEndNeo** [comment]
Hi,

I investigated further and found the issue with CDN server (rawgit) that you used in the HTML

CDN URL: [run_prettify.js @ cdn.rawgit.com](https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js) 
is effectively gets redirected to
CDN URL: [run_prettify.js @ cdn.jsdelivr.net](https://cdn.jsdelivr.net/gh/google/code-prettify@master/loader/run_prettify.js)

The redirect is working fine in some networks. but unfortunately it does NOT happen in other networks!

Could you please replace cdn.rawgit to cdn.jsdelivr

NOTE: Without this change you will miss out many users who won't be able to read the code and leave the site. Most of them won't take a pain of fixing the site to see what's inside!

You have done a great work, don't miss out a large community due to CDN issue!

Thanks
